import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GridDistortion from "../components/GridDistortion";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative bg-black text-white">
        <div className="fixed inset-0 z-[-1] pointer-events-none opacity-30 mix-blend-lighten">
          <GridDistortion 
            imageSrc="/bg.jpg"
            grid={15}
            mouse={0.1}
            strength={0.15}
            relaxation={0.9}
          />
        </div>
        <div className="relative z-10 w-full flex-grow">
          {children}
        </div>
      </body>
    </html>
  );
}
